version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: rpg-postgre
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rpg@park
      POSTGRES_DB: rpg-de-mesa
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rede-rpg-mesa

volumes:
  postgres-data:

networks:
  rede-rpg-mesa: