/** D&D 5e PHB prices — translated to PT-BR */
export const PRICE_ITEMS_SEED = [
  // ─── COMIDA & BEBIDA ────────────────────────────────────────────────────────
  { slug: 'food-bread',          name: 'Pão (1 unidade)',         category: 'food',      priceGp: 0.02,  priceLabel: '2 pc' },
  { slug: 'food-cheese',         name: 'Queijo (pedaço)',         category: 'food',      priceGp: 0.01,  priceLabel: '1 pc' },
  { slug: 'food-chicken',        name: 'Galinha assada',          category: 'food',      priceGp: 0.03,  priceLabel: '3 pc' },
  { slug: 'food-meat',           name: 'Carne (porção)',          category: 'food',      priceGp: 0.30,  priceLabel: '3 pp' },
  { slug: 'food-meal-poor',      name: 'Refeição (precária)',     category: 'food',      priceGp: 0.03,  priceLabel: '3 pc' },
  { slug: 'food-meal-modest',    name: 'Refeição (modesta)',      category: 'food',      priceGp: 0.20,  priceLabel: '2 pp' },
  { slug: 'food-meal-good',      name: 'Refeição (boa)',          category: 'food',      priceGp: 0.80,  priceLabel: '8 pp' },
  { slug: 'food-daily-poor',     name: 'Sustento diário (mísero)',category: 'food',      priceGp: 0.10,  priceLabel: '1 pp', notes: 'por dia' },
  { slug: 'food-daily-modest',   name: 'Sustento diário (simples)',category: 'food',     priceGp: 0.50,  priceLabel: '5 pp', notes: 'por dia' },
  { slug: 'food-daily-comfort',  name: 'Sustento diário (comfortável)',category: 'food', priceGp: 2.00,  priceLabel: '2 po', notes: 'por dia' },
  { slug: 'food-daily-wealthy',  name: 'Sustento diário (abastado)',category: 'food',    priceGp: 4.00,  priceLabel: '4 po', notes: 'por dia' },
  { slug: 'drink-beer',          name: 'Cerveja (caneca)',        category: 'food',      priceGp: 0.04,  priceLabel: '4 pc' },
  { slug: 'drink-mead',          name: 'Hidromel (caneca)',       category: 'food',      priceGp: 0.05,  priceLabel: '5 pc' },
  { slug: 'drink-wine-common',   name: 'Vinho comum (garrafa)',   category: 'food',      priceGp: 0.20,  priceLabel: '2 pp' },
  { slug: 'drink-wine-fine',     name: 'Vinho fino (garrafa)',    category: 'food',      priceGp: 10.00, priceLabel: '10 po' },
  { slug: 'food-rations',        name: 'Rações (por dia)',        category: 'food',      priceGp: 0.50,  priceLabel: '5 pp', notes: 'por dia' },
  { slug: 'inn-poor',            name: 'Estalagem (simples)',     category: 'food',      priceGp: 0.70,  priceLabel: '7 pc', notes: 'por noite' },
  { slug: 'inn-modest',          name: 'Estalagem (modesta)',     category: 'food',      priceGp: 0.50,  priceLabel: '5 pp', notes: 'por noite' },
  { slug: 'inn-comfortable',     name: 'Estalagem (confortável)', category: 'food',      priceGp: 8.00,  priceLabel: '8 po', notes: 'por noite' },
  { slug: 'inn-wealthy',         name: 'Estalagem (luxuosa)',     category: 'food',      priceGp: 20.00, priceLabel: '20 po', notes: 'por noite' },

  // ─── ARMAS ──────────────────────────────────────────────────────────────────
  { slug: 'weapon-club',         name: 'Clava',                  category: 'weapon',    priceGp: 0.10,  priceLabel: '1 pp' },
  { slug: 'weapon-dagger',       name: 'Adaga',                  category: 'weapon',    priceGp: 2.00,  priceLabel: '2 po' },
  { slug: 'weapon-greatclub',    name: 'Clava longa',            category: 'weapon',    priceGp: 0.20,  priceLabel: '2 pp' },
  { slug: 'weapon-handaxe',      name: 'Machadinha',             category: 'weapon',    priceGp: 5.00,  priceLabel: '5 po' },
  { slug: 'weapon-javelin',      name: 'Dardo',                  category: 'weapon',    priceGp: 0.50,  priceLabel: '5 pp' },
  { slug: 'weapon-mace',         name: 'Maça',                   category: 'weapon',    priceGp: 5.00,  priceLabel: '5 po' },
  { slug: 'weapon-quarterstaff', name: 'Cajado',                 category: 'weapon',    priceGp: 0.20,  priceLabel: '2 pp' },
  { slug: 'weapon-spear',        name: 'Lança',                  category: 'weapon',    priceGp: 1.00,  priceLabel: '1 po' },
  { slug: 'weapon-shortbow',     name: 'Arco curto',             category: 'weapon',    priceGp: 25.00, priceLabel: '25 po' },
  { slug: 'weapon-battleaxe',    name: 'Machado de batalha',     category: 'weapon',    priceGp: 10.00, priceLabel: '10 po' },
  { slug: 'weapon-flail',        name: 'Mangual',                category: 'weapon',    priceGp: 10.00, priceLabel: '10 po' },
  { slug: 'weapon-glaive',       name: 'Glaive',                 category: 'weapon',    priceGp: 20.00, priceLabel: '20 po' },
  { slug: 'weapon-greataxe',     name: 'Machado grande',         category: 'weapon',    priceGp: 30.00, priceLabel: '30 po' },
  { slug: 'weapon-greatsword',   name: 'Espadão',                category: 'weapon',    priceGp: 50.00, priceLabel: '50 po' },
  { slug: 'weapon-halberd',      name: 'Alabarda',               category: 'weapon',    priceGp: 20.00, priceLabel: '20 po' },
  { slug: 'weapon-longsword',    name: 'Espada longa',           category: 'weapon',    priceGp: 15.00, priceLabel: '15 po' },
  { slug: 'weapon-maul',         name: 'Malho',                  category: 'weapon',    priceGp: 10.00, priceLabel: '10 po' },
  { slug: 'weapon-rapier',       name: 'Rapieira',               category: 'weapon',    priceGp: 25.00, priceLabel: '25 po' },
  { slug: 'weapon-shortsword',   name: 'Espada curta',           category: 'weapon',    priceGp: 10.00, priceLabel: '10 po' },
  { slug: 'weapon-longbow',      name: 'Arco longo',             category: 'weapon',    priceGp: 50.00, priceLabel: '50 po' },
  { slug: 'weapon-crossbow-hb',  name: 'Besta pesada',           category: 'weapon',    priceGp: 50.00, priceLabel: '50 po' },
  { slug: 'weapon-crossbow-lt',  name: 'Besta leve',             category: 'weapon',    priceGp: 25.00, priceLabel: '25 po' },
  { slug: 'weapon-crossbow-hd',  name: 'Besta de mão',           category: 'weapon',    priceGp: 75.00, priceLabel: '75 po' },
  { slug: 'weapon-trident',      name: 'Tridente',               category: 'weapon',    priceGp: 5.00,  priceLabel: '5 po' },
  { slug: 'weapon-warhammer',    name: 'Martelo de guerra',      category: 'weapon',    priceGp: 15.00, priceLabel: '15 po' },
  { slug: 'weapon-whip',         name: 'Chicote',                category: 'weapon',    priceGp: 2.00,  priceLabel: '2 po' },
  { slug: 'weapon-arrow-20',     name: 'Flechas (20)',           category: 'weapon',    priceGp: 1.00,  priceLabel: '1 po' },
  { slug: 'weapon-bolt-20',      name: 'Virotes de besta (20)',  category: 'weapon',    priceGp: 1.00,  priceLabel: '1 po' },

  // ─── ARMADURAS ──────────────────────────────────────────────────────────────
  { slug: 'armor-padded',        name: 'Acolchoada (CA 11)',     category: 'armor',     priceGp: 5.00,    priceLabel: '5 po' },
  { slug: 'armor-leather',       name: 'Couro (CA 11)',          category: 'armor',     priceGp: 10.00,   priceLabel: '10 po' },
  { slug: 'armor-studded',       name: 'Couro batido (CA 12)',   category: 'armor',     priceGp: 45.00,   priceLabel: '45 po' },
  { slug: 'armor-hide',          name: 'Peles (CA 12)',          category: 'armor',     priceGp: 10.00,   priceLabel: '10 po' },
  { slug: 'armor-chain-shirt',   name: 'Camisola de malha (CA 13)',category: 'armor',   priceGp: 50.00,   priceLabel: '50 po' },
  { slug: 'armor-scale',         name: 'Cota de escamas (CA 14)',category: 'armor',     priceGp: 50.00,   priceLabel: '50 po' },
  { slug: 'armor-breastplate',   name: 'Peitoral (CA 14)',       category: 'armor',     priceGp: 400.00,  priceLabel: '400 po' },
  { slug: 'armor-half-plate',    name: 'Meia armadura (CA 15)',  category: 'armor',     priceGp: 750.00,  priceLabel: '750 po' },
  { slug: 'armor-ring',          name: 'Cota de anéis (CA 14)',  category: 'armor',     priceGp: 30.00,   priceLabel: '30 po' },
  { slug: 'armor-chain-mail',    name: 'Cota de malha (CA 16)',  category: 'armor',     priceGp: 75.00,   priceLabel: '75 po' },
  { slug: 'armor-splint',        name: 'Armadura de tiras (CA 17)',category: 'armor',   priceGp: 200.00,  priceLabel: '200 po' },
  { slug: 'armor-plate',         name: 'Armadura de placas (CA 18)',category: 'armor',  priceGp: 1500.00, priceLabel: '1.500 po' },
  { slug: 'armor-shield',        name: 'Escudo (+2 CA)',         category: 'armor',     priceGp: 10.00,   priceLabel: '10 po' },

  // ─── POÇÕES ─────────────────────────────────────────────────────────────────
  { slug: 'potion-healing',      name: 'Poção de cura',          category: 'potion',    priceGp: 50.00,   priceLabel: '50 po',   notes: 'cura 2d4+2' },
  { slug: 'potion-healing-gr',   name: 'Poção de cura maior',    category: 'potion',    priceGp: 150.00,  priceLabel: '150 po',  notes: 'cura 4d4+4' },
  { slug: 'potion-healing-sup',  name: 'Poção de cura superior', category: 'potion',    priceGp: 500.00,  priceLabel: '500 po',  notes: 'cura 8d4+8' },
  { slug: 'potion-healing-spr',  name: 'Poção de cura suprema',  category: 'potion',    priceGp: 5000.00, priceLabel: '5.000 po',notes: 'cura 10d4+20' },
  { slug: 'potion-antitoxin',    name: 'Antídoto',               category: 'potion',    priceGp: 50.00,   priceLabel: '50 po' },
  { slug: 'potion-climbing',     name: 'Poção de escalada',      category: 'potion',    priceGp: 180.00,  priceLabel: '180 po',  notes: '1 hora' },
  { slug: 'potion-fire-res',     name: 'Poção de resistência',   category: 'potion',    priceGp: 300.00,  priceLabel: '300 po',  notes: '1 hora' },
  { slug: 'potion-speed',        name: 'Poção de velocidade',    category: 'potion',    priceGp: 400.00,  priceLabel: '400 po',  notes: '1 minuto' },
  { slug: 'potion-invisibility', name: 'Poção de invisibilidade',category: 'potion',    priceGp: 180.00,  priceLabel: '180 po',  notes: '1 hora' },
  { slug: 'potion-heroism',      name: 'Poção de heroísmo',      category: 'potion',    priceGp: 180.00,  priceLabel: '180 po',  notes: '1 hora' },
  { slug: 'potion-water-breath', name: 'Poção de fôlego aquático',category: 'potion',   priceGp: 180.00,  priceLabel: '180 po',  notes: '1 hora' },
  { slug: 'potion-elixir',       name: 'Elixir de saúde',        category: 'potion',    priceGp: 120.00,  priceLabel: '120 po' },
  { slug: 'potion-poison',       name: 'Veneno básico (frasco)', category: 'potion',    priceGp: 100.00,  priceLabel: '100 po' },

  // ─── TRANSPORTE ─────────────────────────────────────────────────────────────
  { slug: 'transport-donkey',    name: 'Jumento',                category: 'transport', priceGp: 8.00,    priceLabel: '8 po' },
  { slug: 'transport-pony',      name: 'Pônei',                  category: 'transport', priceGp: 30.00,   priceLabel: '30 po' },
  { slug: 'transport-riding',    name: 'Cavalo de sela',         category: 'transport', priceGp: 75.00,   priceLabel: '75 po' },
  { slug: 'transport-draft',     name: 'Cavalo de tração',       category: 'transport', priceGp: 50.00,   priceLabel: '50 po' },
  { slug: 'transport-warhorse',  name: 'Cavalo de guerra',       category: 'transport', priceGp: 400.00,  priceLabel: '400 po' },
  { slug: 'transport-elephant',  name: 'Elefante',               category: 'transport', priceGp: 200.00,  priceLabel: '200 po' },
  { slug: 'transport-cart',      name: 'Carroça',                category: 'transport', priceGp: 15.00,   priceLabel: '15 po' },
  { slug: 'transport-carriage',  name: 'Carruagem',              category: 'transport', priceGp: 100.00,  priceLabel: '100 po' },
  { slug: 'transport-rowboat',   name: 'Barco a remo',           category: 'transport', priceGp: 50.00,   priceLabel: '50 po' },
  { slug: 'transport-sailing',   name: 'Barco a vela',           category: 'transport', priceGp: 10000.00,priceLabel: '10.000 po' },
  { slug: 'transport-keelboat',  name: 'Quilhate',               category: 'transport', priceGp: 3000.00, priceLabel: '3.000 po' },
  { slug: 'transport-ship',      name: 'Nau (navio grande)',     category: 'transport', priceGp: 10000.00,priceLabel: '10.000 po' },
  { slug: 'transport-horse-rent',name: 'Aluguel de cavalo',      category: 'transport', priceGp: 0.50,    priceLabel: '5 pp', notes: 'por dia' },
  { slug: 'transport-ship-pass', name: 'Passagem de navio',      category: 'transport', priceGp: 0.10,    priceLabel: '1 pp', notes: 'por dia' },
  { slug: 'transport-saddle',    name: 'Sela (montaria)',        category: 'transport', priceGp: 10.00,   priceLabel: '10 po' },
  { slug: 'transport-saddle-war',name: 'Sela (guerra)',          category: 'transport', priceGp: 20.00,   priceLabel: '20 po' },
  { slug: 'transport-feed',      name: 'Ração para animal',      category: 'transport', priceGp: 0.05,    priceLabel: '5 pc', notes: 'por dia' },
] as const;
